name: CMake

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: hendrikmuhs/ccache-action@v1.2

      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install Linux dependencies
        run: |
          sudo sed -i 's/azure\.//' /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install libxrandr-dev libxinerama-dev libxi-dev libxcursor-dev libglew-dev

      - name: Export ccache to path
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -GNinja

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
